name: Android CI

on:
  push:
  workflow_dispatch:

env:
  ANGLE_REPO: whitebelyash/ANGLE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Create libs directory
      run: mkdir ./app/libs

    - name: Download AAR
      uses: dawidd6/action-download-artifact@v11
      with:
        name: angle-aar
        path: ./app/libs
        repo: MojoLauncher/angle-builder
        workflow: blank.yml
        workflow_conclusion: success

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
